# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SGwa8apHpc-tPv-VSd8Ex7CV9N1442WO
"""

# REG.NO : 2126
# NAME : M.HARSHITHA
#DATE : 11-10-2022

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as stat

df = pd.read_csv('/content/Enrollments_28092022.csv')
df

#TASK 1
df.info()

#TASK 2
rows = len(df.axes[0])
print("number of rows :",str(rows))

cols = len(df.axes[1])
print("number of columns:",str(cols))

#TASK 3
plt.hist(df['DEGREE'])
plt.show()

plt.hist(df['INTERMEDIATE'])
plt.show()

plt.hist(df['SSC'])
plt.show()

#TASK 4
courses = ['Data Science','MEAN Stack Web Development ','Cloud Computing Services(AWS)']
students= [156,51,90]
colors = ['c','g','y']
plt.pie(students,labels=courses,colors=colors,startangle=90,explode=(0,0,0),autopct = '%1.2f%%')
plt.axis('equal')
plt.show()

#TASK 5
df['INTERNSHIP'].value_counts()

#TASK 6
print('DEGREE')
print("Mean=",np.mean(df['DEGREE']))
print("Median=",np.median(df['DEGREE']))
print("Mode=",stat.mode(df['DEGREE']))

print('INTERMEDIATE')
print("Mean=",np.mean(df['INTERMEDIATE']))
print("Median=",np.median(df['INTERMEDIATE']))
print("Mode=",stat.mode(df['INTERMEDIATE']))

print('SSC')
print("Mean=",np.mean(df['SSC']))
print("Median=",np.median(df['SSC']))
print("Mode=",stat.mode(df['SSC']))

#TASK 7
cv= lambda x: np.std(x, ddof=1)/np.mean(x)*100

print('DEGREE')
print("Range=",max(df['DEGREE'])-min(df['DEGREE']))
print("Co-efficient of Variation=",cv(df['DEGREE']))
df['DEGREE'].describe()

print('INTERMEDIATE')
print("Range=",max(df['INTERMEDIATE'])-min(df['INTERMEDIATE']))
print("Co-efficient of Variation=",cv(df['INTERMEDIATE']))
df['INTERMEDIATE'].describe()

print('SSC')
print("Range=",max(df['SSC'])-min(df['SSC']))
print("Co-efficient of Variation=",cv(df['SSC']))
df['SSC'].describe()

import scipy.stats as stats

#TASK 8
print("Standard Scores of Degree")
print(stats.zscore(df['DEGREE']))

print("Standard Scores of Intermediate")
print(stats.zscore(df['INTERMEDIATE']))

print("Standard Scores of SSC")
print(stats.zscore(df['SSC']))

#TASK 9
plt.boxplot(df['DEGREE'])
plt.show()

plt.boxplot(df['INTERMEDIATE'])
plt.show()

plt.boxplot(df['SSC'])
plt.show()

#outliers function
def outlier(a):
  q1 = np.quantile(a,0.25)
  q3 = np.quantile(a,0.75)
  med = np.median(a)
  iqr = q3-q1
  upper_bound = q3+(1.5*iqr)
  lower_bound = q1-(1.5*iqr)
  print(iqr,upper_bound,lower_bound)
  print("Inter Quartile Range:",iqr)
  outliers = a[(a<= lower_bound) |(a>= upper_bound) ]
  print("the following are the outliers in boxplot:\n{}".format(outliers))

outlier(df['DEGREE'])

outlier(df['INTERMEDIATE'])

outlier(df['SSC'])

#TASK 10
def func(b):
  q9 = np.quantile(b,0.9)
  li = b[b==q9]
  print("no.of students with 90% percentile:",li.count())

func(df['DEGREE'])

func(df['INTERMEDIATE'])

func(df['SSC'])

